platform :ios, '13.0'

source 'git@github.com:Optable/optable-cocoapods.git'
source 'https://cdn.cocoapods.org/'

project 'demo-ios-swift.xcodeproj'

target 'demo-ios-swift' do
  use_frameworks!

  pod 'OptableSDK'
  pod 'Google-Mobile-Ads-SDK'

  target 'demo-ios-swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demo-ios-swiftUITests' do
    # Pods for testing
  end

end
