platform :ios, '14.0'

source 'https://cdn.cocoapods.org/'

project 'demo-ios-objc.xcodeproj'

target 'demo-ios-objc' do
  use_frameworks!

  # Switch below to use officially released OptableSDK pod instead:
  pod 'OptableSDK', :path => "../"
  #pod 'OptableSDK'

  pod 'Google-Mobile-Ads-SDK'

  target 'demo-ios-objcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demo-ios-objcUITests' do
    # Pods for testing
  end

end
