platform :ios, '15.0'

source 'https://cdn.cocoapods.org/'

project 'demo-ios-objc.xcodeproj'

target 'demo-ios-objc' do
  use_frameworks!

  # Switch below to use officially released OptableSDK pod instead:
  pod 'OptableSDK', :path => "../"
  #pod 'OptableSDK'

  pod 'Google-Mobile-Ads-SDK'

end
