platform :ios, '14.0'

source 'git@github.com:Optable/optable-cocoapods.git'
source 'https://cdn.cocoapods.org/'

project 'demo-ios-objc.xcodeproj'

target 'demo-ios-objc' do
  use_frameworks!

  pod 'OptableSDK'
  pod 'Google-Mobile-Ads-SDK'

  target 'demo-ios-objcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demo-ios-objcUITests' do
    # Pods for testing
  end

end
